#!/usr/bin/env python3
import sys
import lmstudio as lms


def main():
    prompt = sys.stdin.read().strip()
    if not prompt:
        sys.exit(1)

    model = lms.llm('phi-4-mini-instruct')

    prediction_stream = model.respond_stream(prompt)

    try:
        for fragment in prediction_stream:
            print(fragment.content, end="")
    except:
        prediction_stream.cancel()

    print()

if __name__ == "__main__":
    main()
